### ISSUE TITLE
Required radio group failing validation when valid

### ISSUE THREAD

**Issue by ga-dan** [Textalk/angular-schema-form#430] opened 2015-06-15 13:48 UTC
Hi there,

First of all, thank you for the work you do on this awesome project.

While experimenting a bit, I bumped into what seems to be an issue with the `required` validation on a `radios` field.

When I attempt to validate a form that contains a `required` `radios` field, and I have _not_ selected any of the radio buttons in the field, the `required` validation fails as expected.  If, after the validation failure occurs, I then select one of the radio buttons and attempt to validate the form again, the form validation fails again, even though an option in the required radio group is selected.

It seems that, when the form is in this state, I can get the validation to pass only by selecting each and every radio button in the group, one at a time, and then validating the form again.

I'm able to reproduce the issue at http://jsfiddle.net/gdcwy8hc/ with the following steps:

1. Without selecting any of the radio buttons, click the "Validate" button. The `required` validation fails as expected.
2. After the validation fails, select one of the radio buttons, and click the "Validate" button again. The form validation fails again, even though one of the options is selected.

Hope this is helpful. :)

Thanks again for the awesome work you do!

**Comment by stramel** [comment] 2015-06-25 19:07
I am able to reproduce this in the jsfiddle.

I ran into a related issue just now where since the `radios` don't have the `required` attribute on them they are marked as valid in angular's form validation. The form is never marked invalid to angular. You can see what I have explained in this https://jsfiddle.net/9rjmawg6/

I thought this could be solved pretty easily by using `ng-required` but then I run into many complications and end up at the same point of @ga-dan even with the angular validation. So it seems like there may be an issue there.

**Comment by aitboudad** [comment] 2015-07-22 08:36
@davidlgj can you look into this issue please :) ?

**Comment by morganmccrory** [comment] 2015-08-07 21:08
Was a solution ever found for this? Running into a similar error, except it only validates when the last radio button is clicked.

**Comment by bruderol** [comment] 2015-08-11 11:28
I just wanted to file the same issue, and run over this issue here.
We encountered the same problem with required enum fields and radio buttons.
Validation does not validate properly which blocks the user from sending the form.

For us this is a blocking issue, which will not allow us to use SchemaForm, which is a pity, because SchemaForm is such a great thing! Many compliments to the developers, it is realy amazing!
It would be great if you could have a look at this issue and fix it, which would help us to use SchemaForm in our project.
Can somebody look at this please?

See following JsFiddle reproducing it (once again):
http://jsfiddle.net/bruderol/9ebmvrqj/

Thanks for some feedback whether someone can fix this or if we should try to fix it on our own.

**Comment by davidlgj** [comment] 2015-08-11 11:33
@bruderol you are using JSON Schema v3 syntax of required, changing it to version 4 (as tv4 uses) seems to work for me, see http://jsfiddle.net/9ebmvrqj/7/

**Comment by davidlgj** [comment] 2015-08-11 11:35
Hi @ga-dan hmmm... very weird. I'll try to look at it this week. I'll be back with updates!

**Comment by bruderol** [comment] 2015-08-11 11:45
@davidlgj 
Wow, thanks for the fast reply.
Sorry, my fiddle link in my comment was first wrong (the example was not the one with radios, I copied the wrong link), seems you clicked faster on it than I could correct it (now the link in the comment is right).

Following fiddle contains the example with the radios:
http://jsfiddle.net/bruderol/2przo27n/

And also changing the required part to v4 required fields in array did not fix the problem.
Thanks for looking at it.

**Comment by davidlgj** [comment] 2015-08-11 11:47
@bruderol :D haha yes that is the same bug!

**Comment by jbsaff** [comment] 2015-08-13 18:45
It looks like tv4 is called and returns valid:true by the sfValidator.  However, if the field was previously marked invalid, the form doesn't get marked valid until after multiple changes to the field value (selecting between the options twice usually does it for me).  I see the same behavior regardless of whether the field is listed as required in the schema or in the form.

**Comment by leader80** [comment] 2015-08-21 11:05
.. same issue here... any solution found?

**Comment by mutharasus** [comment] 2015-08-25 15:02
any solution or work around ? I have hit the same issue

**Comment by bruderol** [comment] 2015-08-28 13:11
@davidlgj any updates on this bug? seems many people are interested in a fix or workaround.

**Comment by davidlgj** [comment] 2015-08-30 18:55
@bruderol Yes, been busy with the new builder, but you're right this should be higher priority. I've been looking into it and I have a solution in mind. Will try to get it done soonish

**Comment by davidlgj** [comment] 2015-09-04 11:47
@stramel @ga-dan @aitboudad @bruderol @leader80 @jbsaff @morganmccrory I think I have a solution. It tied into #520. 

There is a branch with a fix here https://github.com/Textalk/angular-schema-form/tree/hotfix/0.8.9

I would really appreciate some help testing it out, so if you have time please do!

**Comment by davidlgj** [comment] 2015-09-18 09:06
@stramel @ga-dan @aitboudad @bruderol @leader80 @jbsaff @morganmccrory

The fix is now out in 0.8.9!

**Closed by davidlgj** 2015-09-18 09:06 UTC
