### ISSUE TITLE
Disable validation for elements out of current form

### ISSUE THREAD

**Issue by burdiuz** [Textalk/angular-schema-form#198] opened 2015-01-06 18:09 UTC
Hi!
I have 2 form settings for Canada and US addresses, they are identical except of State/Province enumeration. Both forms are connected to same model object. When user switches country, specific form is shown. When I launch validation with default country, it works fine. But if I select another country, so new settings loaded and new form elements added  -- it breaks validation because somehow validation goes through all form fields(CA and US have different enumerations for their states/provinces, so value will be invalid for one of them), for both countries even if they its not visible and should not be validated at all. This is confusing because selected country fiends show all fields valid but in total validation fails and "invalid" fields are being nullified with validator.
For now I found 2 solutions
1. make own validation cycle asking each field is it valid
2. change validation event handler in a way that will prevent inactive form fields to be validated.

**Comment by burdiuz** [comment] 2015-01-06 20:17
It seems I've found easy to use solutionb described in this ticket:
https://github.com/Textalk/angular-schema-form/issues/200

**Comment by davidlgj** [comment] 2015-01-07 07:54
Marking it as a duplicate of #200

**Comment by fiddur** [comment] 2015-01-07 08:31
I don't know if proper oneOf-support is implemented for the form yet, but with regards to json-schema and tv4 (the validator) a oneOf-statement in the address could be used, stating that it either should be country "Canada" and matching a certain province, or country "USA"...  In either case, the validator shouldn't require a field to be set if it isn't marked as "required" in the schema.

**Closed** 2015-01-07 09:24 UTC
Labels: bug, duplicate
