### ISSUE TITLE
Form does not validate itself upon model update

### ISSUE THREAD

**Issue by chesterlau** [Textalk/angular-schema-form#520] opened 2015-08-26 05:18 UTC
Steps to reproduce:
1. Leave the textfield blank and hit submit.
2. The textfield is validated and a required error occurs.
3. I have a "Populate Fields" button which auto populate the textfield via the form model upon clicking it.
4. The required error is still there and I cannot hit submit.

**Comment by davidlgj** [comment] 2015-08-26 05:43
This should be taken care of by `ng-model`. Strange! 

@chesterlau can you give me a form definition and a schema? You can use the demo page if you want and save it as a gist. 

The populate fields button, is it using a `ng-click`? What I'm getting at is if a digest loop is happening or not.

**Comment by chesterlau** [comment] 2015-08-26 07:29
Hey David,

I came out with a quick demo that reflects the problem.
Link:
http://plnkr.co/edit/ITAjAZ2ydAxcUH0ixQGb?p=preview

To reproduce:
1. Click "Save" first.
2. Form validates and you can see name and age are required.
3. Select the dropdown and choose an option.
4. Name and age is auto-populated.
5. Validation errors stay.
6. Cannot submit form.

**Comment by davidlgj** [comment] 2015-08-30 18:54
Just wanted to pop in and say I've been digging in this and the problem is how ASF hooks into the validation cycle of ngModel. To support Angular 1.2 we use `ngModel.$parsers` to trigger validation, which of course aren't fired when model change from the outside. I think I know what needs to be done (probably hook into $formatters as well), try to get it working soon.  Will hopefully fix #430 as well.

**Comment by chesterlau** [comment] 2015-08-31 03:43
Hey David,

Thanks for the update. A quick hack that I can think of at the moment is to call $scope.$broadcast('schemaFormRedraw') and then re-assigning the form model to itself (just to trigger the watch).

All validations will be cleared and the form models will be re-assigned back into the form.

Cheers,
Chester

**Comment by davidlgj** [comment] 2015-09-04 11:38
@chesterlau I think I have a solution, If you have time I would love for you to test it. It's here: https://github.com/Textalk/angular-schema-form/tree/hotfix/0.8.9  

So this started me down a rabbit hole :) I ended up hooking into `ngModel.$formatters` as well for validation. Which worked fine. But it landed me with two problems. First of that is also called the first time we actually render the form, which is often not what we want. Especially if we have fields that are required. I made a global option for this. `validateOnRender` which defaults to `false`. The second problem was that even though the field got validated on model change, no error messages popped up. This led to and option on how to handle pristine fields. 

Anyway please test it if you have the time!

**Comment by chesterlau** [comment] 2015-09-06 23:34
Hey David,

I have tested your fix and it works well here.
When will this change be merged into the dev branch?

Thanks very much.

Cheers,
Chester

**Comment by leader80** [comment] 2015-09-07 10:50
Hi David,

radio buttons are also working for me, I don't see any changes in radio-inline component, are you going to fix also them?

Thanks
G.

**Comment by davidlgj** [comment] 2015-09-18 09:03
@leader80 Oh thanks for noticing otherwise I'd missed the inlines. 

@chesterlau It's now released and in the development branch as well! Thank you for testing.

**Closed by davidlgj** 2015-09-18 09:03 UTC
