### ISSUE TITLE
Validation doesn't work properly when previous item is removed

### ISSUE THREAD

**Issue by aguirrel** [Textalk/angular-schema-form#534] opened 2015-09-06 02:57 UTC
Hi!

Thanks a lot for this amazing component!

I'm working with arrays and I saw a problem.  You can reproduce it following this secuence:

* Go to example page (http://schemaform.io/examples/bootstrap-example.html)
* Select "array" example
* Add a new comment using "new" bottom
* In the first comment, write "a" in Name field and then delete it, so it gets "red" and raises "Required".
* Go to second comment, write "b" in Name field, it gets valid and green
* Delete first comment

Expected: Name field in green color
Problem: First comment Field Name is red and invalid, if you bradcast "schemaFormValidate" it is still wrong.  Form itseld is invalid.

Thanks a lot!

Best regards,

Luis

**Comment by davidlgj** [comment] 2015-09-06 15:52
Oh, that was strange! Marking it as a bug. And a serious one as well!

**Comment by aguirrel** [comment] 2015-09-13 02:47
Hi @davidlgj any update about this bug? Thanks a lot!

**Comment by davidlgj** [comment] 2015-09-18 10:23
@aguirrel It looks like I have accidentally fixed this with the latest release. It had some bugfixes in it. Especially one that fixes a bug that stopped it from validating when something changes the model that isn't the actual input or textarea. 

Anyways I can no longer reproduce it. I've updated the demo page to 0.8.9. If you still experience a problem feel free to open the issue again!

**Closed by davidlgj** 2015-09-18 10:23 UTC
Labels: bug

**Comment by aguirrel** [comment] 2015-09-18 11:17
Yeah! It works great now! Thanks a lot! It's the best form creation component!
