### ISSUE TITLE
Form validity after schema update

### ISSUE THREAD

**Issue by aymericfr** [Textalk/angular-schema-form#182] opened 2014-12-11 11:16 UTC
Hello,
Here is my issue: depending on some user inputs, the schema is reloaded so the form re-renders. But in this case, the validation always fails as if there were some errors remaining from the previous schema.
Am I missing something here?

**Comment by burdiuz** [comment] 2015-01-06 18:30
May be we have same issue
https://github.com/Textalk/angular-schema-form/issues/198

**Comment by davidlgj** [comment] 2015-01-07 09:23
Yes seems to be a duplicate of #198 and #200

**Closed by davidlgj** 2015-01-07 09:23 UTC
Labels: duplicate
