### ISSUE TITLE
after htmlClass is added the fields becomes unclickable

### ISSUE THREAD

**Issue by navjinder** [Textalk/angular-schema-form#215] opened 2015-01-15 17:00 UTC
When bootstrap classes are added using htmlClass to the form json for layout. The field becomes unclickable only keyboard tab works.

```json
{
"key": "requester",
"type": "text",
"placeholder": "Full Name",
"htmlClass": "col-md-10",
"feedback": false
 }
```

**Comment by stramel** [comment] 2015-01-15 17:04
@navjinder What version of schemaForm are you using?

**Comment by navjinder** [comment] 2015-01-15 17:35
Hi 

I am using the latest version I downloaded it yesterday from [GitHub.](https://github.com/Textalk/angular-schema-form/tree/master/dist). THere is no version number in the file header. Thanks.

**Comment by davidlgj** [comment] 2015-01-19 08:31
Hi @navjinder,

Its a CSS problem. I tried it on the demo page and indeed it got unclickable, what happens is that  the class  `col-md-10` adds the style rule `float: left;` which caused the next form field to surrounding div to overlap and take all the events. You can see this if you use "inspect element" in the developer tools. 

One solution for you is to just apply "col-md-10" on the next field as well. Closing since its not a bug in schema form

**Closed by davidlgj** 2015-01-19 08:31 UTC
Labels: bug

**Comment by navjinder** [comment] 2015-01-19 14:38
Hi @davidlgj  thanks for the info yes I was able to see that float was causing the issue. So what I did was I have created a special class which do not have the float in it and I have applied it to the last form field which has fixed the error for me.
