### ISSUE TITLE
`schema-form.js` is missing in version "0.7.8"

### ISSUE THREAD

**Issue by mohsen1** [Textalk/angular-schema-form#211] opened 2015-01-13 22:52 UTC
I was using `schema-form.js` (non minified) in my project Swagger Editor. Your recent push (`"0.7.8"`) is missing `schema-form.js` file.  Please add it back with a patch version.

Related to: https://github.com/swagger-api/swagger-editor/issues/296 and https://github.com/swagger-api/swagger-editor/issues/295

Thanks, 
Mohsen

**Comment by stramel** [comment] 2015-01-14 02:18
@mohsen1 I still see the version in version 0.7.8

**Comment by mohsen1** [comment] 2015-01-14 03:41
I don't see it
![screen shot 2015-01-13 at 7 41 02 pm](https://cloud.githubusercontent.com/assets/543633/5733707/25e9496a-9b5c-11e4-8640-303d6af044a1.png)

**Comment by Simomultimedia** [comment] 2015-01-14 06:10
@mohsen1  dist folder contains min files only, you might want to check the source folder for unminified js files. Here https://github.com/Textalk/angular-schema-form/tree/master/src/services if you referring to the schama-form.js services file or here https://github.com/Textalk/angular-schema-form/tree/master/src/directives if you referring to the directive.

**Comment by mohsen1** [comment] 2015-01-14 06:49
`0.7.6` Used to have un-minified `schema-form.js ` in `dist`. I can change my code to point to minified version but I usually include non-mified code in development and minify everything myself. 

In current master [`schema-form.js`](https://github.com/Textalk/angular-schema-form/blob/master/dist/schema-form.js) exists in `dist` actually

**Comment by Dervisevic** [comment] 2015-01-14 06:58
I'm not sure why you're not getting it. I see the unminified schema-form.js in dist here on github in master and in the 0.7.8 tag. I also see it if i download it from releases on gh and i also see it in the bower version, not sure why it's not showing up for you. How are you acquiring ASF?

**Comment by stramel** [comment] 2015-01-14 16:18
@mohsen1 @Dervisevic I am seeing the same thing when running a clean install. I forgot I had been using the custom built files from my PRs.

**Comment by Dervisevic** [comment] 2015-01-15 07:29
Ok guys, we found what it is, bower is incorrectly following the ignore glob, `*.js` is actually going into dist and ignoring the schema-form.js file. Both mine and @davidlgj's understanding is that it should not go into the directory. [This](http://www.globtester.com/#p=eJzT0ssqBgACfQE2&r=eJx9zcENgCAMQNFVDHdhAewutYCiFAxF59fEq3L9ecm3Ll4DJRSZlAIXpRmh1TOOoVTWm1jzCLB9xjF%2FUsZGq4LlTEeIyffMjpVRU8nhZ2rnCm%2B%2FAU1QPok%3D&) also says the same.

Anyways installed versions of 0.7.8 are already doomed so a bower install will be needed. There is no point in fixing that version so we will be going to 0.7.9.

**Comment by Dervisevic** [comment] 2015-01-15 08:15
Ok guys, it's been fixed in b6e4db0e84e9aa1935b3bf01aef8557c957be8a5. I have verified that the 0.7.9 bower install works as intended. Sorry for any inconvenience.

**Closed by Dervisevic** 2015-01-15 08:15 UTC

**Comment by stramel** [comment] 2015-01-15 14:26
@Dervisevic You can test your globs using the following:

Install [globby][glob]

```js
var globby = require('globby');

console.log(globby.sync(['*.js']));
```

[glob]: https://github.com/sindresorhus/globby

**Comment by Dervisevic** [comment] 2015-01-15 14:51
Thanks! That'll come in handy. And this tool confirms what i expected, that bower doesn't quite follow the standard. I have filed an issue there: bower/bower#1663

```
> console.log(globby.sync(['*.js']));
[ 'gulpfile.js', 'karma.conf.js' ]
```

**Comment by stramel** [comment] 2015-01-15 15:32
You're welcome, that tool has saved me many times!
